apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: java-test
spec:
  params:
    - name: url
    - name: revision
      default: master
  steps:
    - name: git-clone
      image: alpine/git
      script: |
        git clone -b $(params.revision) --depth 1 $(params.url) /source
      volumeMounts:
        - name: source
          mountPath: /source
    - name: test
      image: maven:3.3-jdk-8
      workingdir: /source
      script: |
        mvn test
        echo "tests passed with rc=$?"
      volumeMounts:
        - name: m2-repository
          mountPath: /root/.m2
        - name: source
          mountPath: /source
  volumes:
    - name: m2-repository
      emptyDir: {}
    - name: source
      emptyDir: {}
