apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  params:
    - name: repo-url
      default: https://github.com/ibm-cloud-architecture/cloudnative_sample_app
    - name: revision
      default: master
    - name: image-registry
      default: index.docker.io
    - name: image-repository
      default: csantanapr
    - name: image-name
      default: cloudnative_sample_app
  workspaces:
    - name: w
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: w
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: "true"
    - name: build
      runAfter: ["git-clone"]
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: w
      params:
        - name: image
          value: $(params.image-registry)/$(params.image-repository)/$(params.image-name)
