apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: java-test
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: maven:3.3-jdk-8
      workingdir: $(workspaces.source.path)
      script: |
        mvn test
        echo "tests passed with rc=$?"
      volumeMounts:
        - name: m2-repository
          mountPath: /root/.m2
  volumes:
    - name: m2-repository
      emptyDir: {}
